FROM node:14.15
RUN mkdir -p /home/node/app/node_modules && chown -R node:node /home/node/app
WORKDIR /home/node/app
COPY ../package*.json ./
USER node
RUN npm install
ENV ENVIROMENT_ONLINE=true
ENV NODE_ENV=development
COPY --chown=node:node ../ .
RUN npm run build
CMD [ "npm", "run" ,"develop" ]
